config/routes.rb
Rails.application.routes.draw do
    resources :sinistres do
    resources :repartitions, only: [:create, :new]
  end
  resources :repartitions, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/metier.rb
class Metier < ApplicationRecord
  has_many :repartitions
  validates :name, presence: true, uniqueness: true
end

app/models/repartition.rb
class Repartition < ApplicationRecord
  belongs_to :metier
  belongs_to :sinistre
  validates :sinistre, uniqueness: { scope: :metier }
end

app/models/sinistre.rb
class Sinistre < ApplicationRecord
  has_many :repartitions, dependent: :destroy
  has_many :metiers, through: :repartitions
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repartitions_controller.rb
class RepartitionsController < ApplicationController
  before_action :set_repartition, except: [:new, :create]
  before_action :set_sinistre, except: [:destroy]

  def new
    @repartition = Repartition.new
  end

  def create
    @repartition = Repartition.new(repartition_params)
    @repartition.sinistre = Sinistre.find(params[:sinistre_id])
    if @repartition.save
          redirect_to sinistre_path(@repartition.sinistre)
    else
      render :new
    end
  end

  def destroy
    @repartition.destroy
    redirect_to sinistres_path
  end

private

  def repartition_params
    params.require(:repartition).permit(:description, :metier_id)
  end

  def set_repartition
    @repartition = Repartition.find(params[:id].to_i)
  end

  def set_sinistre
    @sinistre = Sinistre.find(params[:sinistre_id].to_i)
  end
end

app/controllers/sinistres_controller.rb
class SinistresController < ApplicationController

before_action :set_sinistre, except: [:index, :new, :create]

  def index
    if params[:query].present?
      @sinistres = Sinistre.where("name ILIKE ?", "%#{params[:query]}%").order("created_at DESC")
    else
      @sinistres = Sinistre.all.order("created_at DESC")
    end
  end

  def create
      @sinistre = Sinistre.new(sinistre_params)
    if @sinistre.save
          redirect_to sinistre_path(@sinistre)
    else
      render :new
    end
  end

  def new
    @sinistre = Sinistre.new
  end

  def show
  end

  private

  def sinistre_params
    params.require(:sinistre).permit(:name, :place, :size, :metiers, :attributions, :picture, :photo , :couverture , :demarches)
  end

  def set_sinistre
    @sinistre = Sinistre.find(params[:id].to_i)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repartitions_helper.rb
module RepartitionsHelper
end

app/helpers/sinistres_helper.rb
module SinistresHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to sinistres_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Nouveau sinistre", "sinistres/new", class: "navbar-wagon-item navbar-wagon-link" %>
  <!--   <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %> -->

    <!-- Avatar with dropdown menu -->
<!--     <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterConstruct</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->

  </head>

  <body>
      <%= render "layouts/navbar" %>
    <div class = "empty">
    </div>
    <%= yield %>
  </body>
</html>

app/views/repartitions/create.html.erb
<h1>Repartitions#create</h1>
<p>Find me in app/views/repartitions/create.html.erb</p>

app/views/repartitions/destroy.html.erb
<h1>Repartitions#destroy</h1>
<p>Find me in app/views/repartitions/destroy.html.erb</p>

app/views/repartitions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Ajouté les corps de métier</h1>
<%= simple_form_for [@sinistre, @repartition] do |f|%>
<%= f.input :description %>
<%= f.association :metier %>
<%= f.submit  'submit', class: 'btn btn-primary'%>
<% end %>
  </div>
  </div>
</div>

app/views/sinistres/_form.html.erb
<%= simple_form_for(@sinistre) do |f| %>
  <%= f.input :name, placeholder: "type de sinistre" %>
  <%= f.input :place, collection: ["Intérieur", "Extérieur"]%>
  <%= f.input :size, collection: ["Small", "Medium","Big"] %>
  <%= f.button :submit, class: "btn btn-primary"  %>

<% end %>

app/views/sinistres/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1518904868869-fbb2cdd0429a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ea451d87e8fb866a1550eb8d156e26a5&auto=format&fit=crop&w=1349&q=80');">
  <div class="banner-content">
    <h1>Un sinistre ?</h1>
    <p>Comment réagir efficacement selon le type de dégats</p>

<div class="md-form active-cyan-2 mb-3">
    <%= form_tag sinistres_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Trouver un type de sinistre"
      %>
    <% end %>
</div>

  </div>
</div>


<div class =container>
  <div class = row>

    <h2 class = 'text-center'>Les sinistres rencontrés</h2>
    <p class = 'text-center'> <i>Trouver de manière efficace les personnes les plus appropriées pour reparer votre bien</i></p>
    <p class = 'text-center'>  ― Selectionnez votre type de sinistre ci-dessous - </p>

    <ul>
      <% @sinistres.each do |i| %>
      <div class="col-xs-12 col-sm-3">
        <li>
          <%= link_to sinistre_path(i) do %>
          <% if i.picture %>

            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path i.picture%>');">
              <div class="card-category">Les plus courants</div>
              <div class="card-description">
                <h2><%= i.name %></h2>
              </div>
            </div>

          <% elsif %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1535463942256-8d1d1bcdf366?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=88a0f2994dd67b4ea17e0e8d0076bb95&auto=format&fit=crop&w=876&q=80')">
              <div class="card-category">New</div>
                <div class="card-description">
                  <h2><%= i.name %></h2>

              </div>
            </div>
          <% end %>
        </li>
      </div>

      <% end %>
      <% end %>
    </ul>
  </div>
</div>

<div class="text-center padded">
  <%= link_to "Votre sinistre n'est pas la ? Créez le ", new_sinistre_path, class: "btn btn-primary" %>
</div>

app/views/sinistres/new.html.erb
<div class="container">

  <div class="row justify-content-md-center">

    <div class="col col-md-2">
    </div>

    <div class="col-md-8">

      <div class="panel panel-primary">
        <div class="panel-heading">
          <h1>Nouveau Sinistre</h1>
        </div>
        <div class="panel-body">
          <%= render 'form' %>  <%= link_to 'Back', sinistres_path %>
        </div>
      </div>

    </div>
    <div class="col col-md-2">
    </div>

  </div>

</div>

app/views/sinistres/show.html.erb
<div class="banner_small" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path @sinistre.picture%>');">
  <div class="banner-content">

    <h1> <%= @sinistre.name %></h1>

  </div>
</div>

<div class=container>
  <div class=row>
    <div class="panel panel-primary">
      <div class="panel-heading">
         <h3> Informations importantes</h3>
      </div>
      <div class="panel-body">
          <ul>
            <% @sinistre.repartitions.each do |repartition| %>
              <li>
                <h3>Qui contacter en premier ?</h3>

                <p> Le <%= repartition.metier.name %> s'occupe à <%= repartition.description %> de la résolution de ce type de sinistre. Il est impératif de contacter un <%= repartition.metier.name %> le plus rapidement possible </p>
                <%= link_to repartition_path(repartition), method: :delete do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>
              </li>
            <% end %>


              <li>
                <h3>Quelles démarches dois-je suivre ?</h3>
                <%= @sinistre.demarches %>
              </li>

              <li>
                <h3>Comment suis-je couvert ?</h3>
                <%= @sinistre.couverture%>
              </li>
          </ul>
      </div>
    </div>
    <%= link_to "Ajouter un intervenant et son importance", new_sinistre_repartition_path(@sinistre) %>
  </div>
</div>